sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Mysql54321
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: waimai-ikaros
  redis:
    host: localhost
    port: 6379
    # password:
    database: 10
  wechat:
    appid: wxe24b4ca3b5aab504
    secret: 8ca7e600b3efc63f606a9531ee30e29f

